from vidmodex.models import Model
from .models import *

Model.register("resnet18")(resnet18)
Model.register("resnet34")(resnet34)
Model.register("resnet50")(resnet50)
Model.register("resnet101")(resnet101)
Model.register("resnet152")(resnet152)
Model.register("vgg11")(vgg11)
Model.register("vgg11_bn")(vgg11_bn)
Model.register("vgg13")(vgg13)
Model.register("vgg13_bn")(vgg13_bn)
Model.register("vgg16")(vgg16)
Model.register("vgg16_bn")(vgg16_bn)
Model.register("vgg19")(vgg19)
Model.register("vgg19_bn")(vgg19_bn)
Model.register("alexnet")(alexnet)
Model.register("efficientnet_b0")(efficientnet_b0)
Model.register("efficientnet_b1")(efficientnet_b1)
Model.register("efficientnet_b2")(efficientnet_b2)
Model.register("efficientnet_b3")(efficientnet_b3)
Model.register("efficientnet_b4")(efficientnet_b4)
Model.register("efficientnet_b5")(efficientnet_b5)
Model.register("efficientnet_b6")(efficientnet_b6)
Model.register("efficientnet_b7")(efficientnet_b7)
Model.register("mobilenet_v2")(mobilenet_v2)
Model.register("shufflenet_v2_x0_5")(shufflenet_v2_x0_5)
Model.register("shufflenet_v2_x1_0")(shufflenet_v2_x1_0)
Model.register("shufflenet_v2_x1_5")(shufflenet_v2_x1_5)
Model.register("shufflenet_v2_x2_0")(shufflenet_v2_x2_0)
Model.register("inception_v3")(inception_v3)

Model.register("densenet121")(densenet121)
Model.register("densenet169")(densenet169)
Model.register("densenet201")(densenet201)
Model.register("densenet161")(densenet161)
Model.register("googlenet")(googlenet)
Model.register("mnasnet0_5")(mnasnet0_5)
Model.register("mnasnet0_75")(mnasnet0_75)
Model.register("mnasnet1_0")(mnasnet1_0)
Model.register("mnasnet1_3")(mnasnet1_3)
Model.register("resnext50_32x4d")(resnext50_32x4d)
Model.register("resnext101_32x8d")(resnext101_32x8d)
Model.register("wide_resnet50_2")(wide_resnet50_2)
Model.register("wide_resnet101_2")(wide_resnet101_2)
Model.register("squeezenet1_0")(squeezenet1_0)
Model.register("squeezenet1_1")(squeezenet1_1)
