pipeline: "dfme"
experiment: "dfme_cifar100_gan32_victim_efficientnet_b7_clone_efficientnet_b7"
model:
  victim: 
    name: "efficientnet_b7"
    weight: "weights/pretrained/efficientnet/efficientnet_b7_cifar100_1.0k.ckpt"
    weight_uri: False
    topk: 100
    subpart: "state_dict"
    remap_keys: "s/^victim\\.//"
    model_kwargs:
      num_classes: 100
  clone: 
    name: "efficientnet_b7"
    weight: None #"weights/pretrained/state_dicts/cifar_10_cifar_resnet18.pt"
    weight_uri: False
    topk: 100
    subpart: "full"
    remap_keys: None
    model_kwargs:
      num_classes: 100
  generator: 
    name: "generator32"
    weight: None
    weight_uri: False
    remap_keys: None
    model_kwargs: {}
target_dataset:
  name: "cifar100"
  num_classes: 100
train_dataset:
  name: "cifar100"
  num_classes: 100
  dataset_type: "cifar100"
  init_kwargs:
    root: "../datasets/image/cifar100"
    train: True
val_dataset: 
  name: "cifar100"
  num_classes: 100
  dataset_type: "cifar100"
  init_kwargs:
    root: "../datasets/image/cifar100"
    train: False