pipeline: "dfme"
experiment: "dfme_kin600_tgan_victim_swint_clone_swint"
model:
  victim: 
    name: "swint"
    weight: "weights/pretrained/swint/swin_tiny_patch244_window877_kinetics600_1k.pth"
    weight_uri: False
    topk: 600
    subpart: "state_dict"
    model_kwargs:
      num_classes: 600
  clone: 
    victim: 
    name: "swint"
    weight: None
    weight_uri: False
    topk: 600
    subpart: "state_dict"
    model_kwargs:
      num_classes: 600
  generator: 
    name: "tgan"
    weight: None
    weight_uri: False
    model_kwargs: {}
target_dataset:
  name: "kinetics600"
  num_classes: 600
train_dataset: None
val_dataset: 
  name: "kinetics600"
  num_classes: 600
  dataset_type: "videoDataset"
  init_kwargs:
    dataset_root: "../datasets/video/k600/val"
    dataset_csv: "../datasets/video/k600/kinetics-600-val.csv"