pipeline: "dfme"
experiment: "dfme_mnist_gan28_victim_resnet18_clone_resnet18"
model:
  victim: 
    name: "resnet18"
    weight: "weights/pretrained/resnet/resnet18_mnist_0.025k.ckpt"
    weight_uri: False
    topk: 10
    subpart: "state_dict"
    remap_keys: "s/^victim\\.//"
    model_kwargs:
      num_classes: 10
  clone: 
    name: "resnet18"
    weight: None #"weights/pretrained/state_dicts/cifar_10_cifar_resnet18.pt"
    weight_uri: False
    topk: 10
    subpart: "full"
    remap_keys: None
    model_kwargs:
      num_classes: 10
  generator: 
    name: "generator28"
    weight: None
    weight_uri: False
    remap_keys: None
    model_kwargs: {}
target_dataset:
  name: "mnist"
  num_classes: 10
train_dataset:
  name: "mnist"
  num_classes: 10
  dataset_type: "mnist"
  init_kwargs:
    root: "../datasets/image/mnist"
    train: True
val_dataset: 
  name: "mnist"
  num_classes: 10
  dataset_type: "mnist"
  init_kwargs:
    root: "../datasets/image/mnist"
    train: False