pipeline: "dfme"
experiment: "dfme_something_something_v2_tgan_victim_swint_clone_swint"
model:
  victim: 
    name: "swint"
    weight: "weights/pretrained/swint/swin_tiny_patch244_window877_smthg_smthg_v2_1k.pth"
    weight_uri: False
    topk: 174
    subpart: "state_dict"
    model_kwargs:
      num_classes: 174
  clone: 
    name: "swint"
    weight: None
    weight_uri: False
    topk: 174
    subpart: "state_dict"
    model_kwargs:
      num_classes: 174
  generator: 
    name: "tgan"
    weight: None
    weight_uri: False
    model_kwargs: {}
target_dataset:
  name: "something-something-v2"
  num_classes: 174
train_dataset: None
val_dataset: 
  name: "something-something-v2"
  num_classes: 174
  dataset_type: "videoDataset"
  init_kwargs:
    dataset_root: "../datasets/video/something-something-v2/20bn-something-something-v2"
    dataset_csv: "../datasets/video/something-something-v2/something-something-v2-val.csv"