pipeline: "dfme"
experiment: "dfme_kin400_tgan_victim_swint_clone_vivit"
model:
  victim: 
    name: "swint"
    weight: "weights/pretrained/swint/swin_tiny_patch244_window877_kinetics400_1k.pth"
    weight_uri: False
    topk: 400
    subpart: "state_dict"
    model_kwargs: {}
  clone: 
    name: "vivit"
    weight: None
    weight_uri: False
    model_kwargs:
      image_size: 224
      patch_size: 16
      num_classes: 400
      num_frames: 16
  generator: 
    name: "tgan"
    weight: None
    weight_uri: False
    model_kwargs: {}
target_dataset:
  name: "kinetics400"
  num_classes: 400
train_dataset: None
val_dataset: 
  name: "kinetics400"
  num_classes: 400
  dataset_type: "videoDataset"
  init_kwargs:
    dataset_root: "../datasets/video/k400/val"
    dataset_csv: "../datasets/video/k400/kinetics-400-val.csv"