pipeline: "dfme"
experiment: "dfme_caltech256_gan256_victim_efficient_b7_clone_efficient_b7"
model:
  victim: 
    name: "efficientnet_b7"
    weight: "weights/pretrained/efficientnet/efficientnet_b7_caltech256_1.0k.ckpt"
    weight_uri: False
    topk: 256
    subpart: "state_dict"
    remap_keys: "s/^victim\\.//"
    model_kwargs:
      num_classes: 256
  clone: 
    name: "efficientnet_b7"
    weight: None #"weights/pretrained/efficientnet/efficientnet_b7_cifar100_1.0k.ckpt"
    weight_uri: False
    topk: 256
    subpart: "full"
    remap_keys: None
    model_kwargs:
      num_classes: 256
  generator: 
    name: "generator256"
    weight: None
    weight_uri: False
    remap_keys: None
    model_kwargs: {}
target_dataset:
  name: "caltech256"
  num_classes: 256
train_dataset:
  name: "caltech256"
  num_classes: 256
  dataset_type: "caltech256"
  init_kwargs:
    root: "../datasets/image/caltech256"
    train: True
val_dataset: 
  name: "caltech256"
  num_classes: 256
  dataset_type: "caltech256"
  init_kwargs:
    root: "../datasets/image/caltech256"
    train: False