pipeline: "shap"
experiment: "shap_something_something_v2_condtgan_victim_swint_clone_swint"
model:
  victim: 
    name: "swint"
    weight: "weights/pretrained/swint/swin_tiny_patch244_window877_smthg_smthg_v2_1k.pth"
    weight_uri: False
    topk: 174
    subpart: "state_dict"
    model_kwargs:
      num_classes: 174
  clone: 
    name: "swint"
    weight: None
    weight_uri: False
    topk: 174
    subpart: "state_dict"
    model_kwargs:
      num_classes: 174
  generator: 
    name: "condtgan"
    weight: None
    weight_uri: False
    model_kwargs:
      num_classes: 174
  discriminator:
    name: "shapdiscriminator3D"
    weight: None
    weight_uri: False
    model_kwargs:
      n_channels: 3
      out_channels: 1
      n_classes: 174
      width_multiplier: 1
      trilinear: True
      prob_out: True 
      use_ds_conv: False
target_dataset:
  name: "something-something-v2"
  num_classes: 174
train_dataset: None
val_dataset: 
  name: "something-something-v2"
  num_classes: 174
  dataset_type: "videoDataset"
  init_kwargs:
    dataset_root: "../datasets/video/something-something-v2/20bn-something-something-v2"
    dataset_csv: "../datasets/video/something-something-v2/something-something-v2-val.csv"
shap:
  max_evals: 64
  logits: False
  input_shape: [3, 16, 224, 224]
  model_type: "video"
  batch_size: 32      # This is for each device
  prob_validate: False
config_args:
  optimize_prob: True
  lr_D: 0.0001
  dis_optimizer: "adam"
  shap_iter: 3
  shap_prob_iter: 5
  max_eval_steps: [0.1, 0.2, 0.4, 0.5]
  max_eval_gamma: 0.5
  max_eval_thresh: 16
  min_shap_sigma: 0.2
  